### PR TITLE
AzeorthDoxygen

### PR DESCRIPTION
**Pull request by heyitsbench**

### CODE REVIEW

**Comment by heyitsbench** [comment]
@Kitzunu I beg of you

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
*approved from mobile github noises*

**Comment by acidmanifesto** [comment]
Tanhk yuo fro teh rP!

**Comment by Kitzunu** [comment]
Wont make a difference unless I remember to change it locally too when I generate the docs 😅 but I will try to remember

**Pull request merged**
